
[#idp-mgmt-docs]
= identity configuration management for Kubernetes documentation (Technology Preview)

[IMPORTANT]
====
The identity configuration management for Kubernetes is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/. 
====

The identity configuration management for Kubernetes is a software operator that enhances cluster fleet management. It enables you to quickly and easily propagate OAuth authentication configuration across your fleet of OpenShift Container Platform clusters regardless of cloud provider or data center.

See the following documentation:

- xref:./requirements.adoc#requirements-and-recommendations[Requirements and recommendations]
- xref:./install_connected.adoc#installing-while-connected-online[Installing while connected online]
- xref:./install_disconnected.adoc#installing-disconnected[Installing while not connected online]
- xref:./quick_start.adoc#getting-started[Getting started]
- xref:./uninstall.adoc#uninstalling[Uninstalling]
- xref:./troubleshooting.adoc#troubleshooting[Troubleshooting]
