[#installing-while-connected-online]
= Installing while connected online

The identity configuration management for Kubernetes operator is installed with Operator Lifecycle Manager, which manages the installation, upgrade, and removal of the components that encompass the identity configuration management for Kubernetes.

**Required access:** Cluster administrator

**Important:** For OpenShift Container Platform Dedicated environment, you must have `cluster-admin` permissions. By default `dedicated-admin` role does not have the required permissions to create namespaces in the OpenShift Container Platform Dedicated environment. 

- By default, the identity configuration management components are installed on worker nodes of your OpenShift Container Platform cluster without any additional configuration. You can install the identity configuration management onto worker nodes by using the OpenShift Container Platform OperatorHub web console interface, or by using the OpenShift Container Platform CLI.

//Check on this - I think IDP can run on all infra 
- If you have configured your OpenShift Container Platform cluster with infrastructure nodes, you can install the identity configuration management onto those infrastructure nodes by using the OpenShift Container Platform CLI with additional resource parameters. Not all components have infrastructure node support, so some worker nodes are still required when installing identity configuration management for Kubernetes on infrastructure nodes. See the _Installing the 
identity configuration management on infrastructure node_ section for those details.

* <<connect-prerequisites,Prerequisites>>
* <<confirm-ocp-installation,Confirm your OpenShift Container Platform installation>>
* <<installing-from-the-operatorhub,Installing from the OperatorHub web console interface>>
* <<installing-from-the-cli,Installing from the OpenShift Container Platform CLI>>
* <<installing-on-infra-node,Installing the on infrastructure nodes>>

[#connect-prerequisites]
== Prerequisites

Before you install identity configuration management for Kubernetes, see the following requirements:

* Your RedHat OpenShift Container Platform cluster must have access to the identity configuration management for Kubernetes operator in the OperatorHub catalog from the OpenShift Container Platform console. 

* You need access to the https://catalog.redhat.com/software/containers/search?p=1&application_categories_list=Container%20Platform%20%2F%20Management[catalog.redhat.com].

* OpenShift Container Platform version 4.6, or later, must be deployed in your environment, and you must be logged into with the OpenShift Container Platform CLI. OpenShift Container Platform version 4.6, or later, must be deployed in your environment, and you must be logged into with the OpenShift Container Platform CLI. See the following install documentation for OpenShift Container Platform: 

  - https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/installing/index[OpenShift Container Platform version 4.8]
  - https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/installing/index[OpenShift Container Platform version 4.7]
  - https://docs.openshift.com/container-platform/4.6/welcome/index.html[OpenShift Container Platform version 4.6] 

* Your OpenShift Container Platform command line interface (CLI) must be configured to run `oc` commands. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the CLI] for information about installing and configuring the OpenShift Container Platform CLI.

* Your OpenShift Container Platform permissions must allow you to create a namespace.

* You must have an Internet connection to access the dependencies for the operator.

* To install in a OpenShift Container Platform Dedicated environment, see the following:

** You must have the OpenShift Container Platform Dedicated environment configured and running.

** You must have `cluster-admin` authority to the OpenShift Container Platform Dedicated environment where you are installing the operator.

[#confirm-ocp-installation]
== Confirm your OpenShift Container Platform installation

You must have a supported OpenShift Container Platform version, including the registry and storage services, installed and working. For more information about installing OpenShift Container Platform, see the OpenShift Container Platform documentation.

. Verify that identity configuration management for Kubernetes operator is not already installed on your OpenShift Container Platform cluster. The identity configuration management for Kubernetes operator allows only one single installation on each OpenShift Container Platform cluster. Continue with the following steps if there is no installation.

. To ensure that the OpenShift Container Platform cluster is set up correctly, access the OpenShift Container Platform web console with the following command:

+
[source,terminal]
----
kubectl -n openshift-console get route
----
+
See the following example output:
+
[source,terminal]
----
openshift-console console console-openshift-console.apps.new-coral.purple-chesterfield.com               
console   https   reencrypt/Redirect     None
----

. Open the URL in your browser and check the result. If the console URL displays `console-openshift-console.router.default.svc.cluster.local`, set the value for `openshift_master_default_subdomain` when you install OpenShift Container Platform. See the following example of a URL: `https://console-openshift-console.apps.new-coral.purple-chesterfield.com`.

You can proceed to install 
identity configuration management for Kubernetes.

[#installing-from-the-operatorhub]
== Installing from the OperatorHub web console interface

**Best practice:** From the _Administrator_ view in your OpenShift Container Platform navigation, install the OperatorHub web console interface that is provided with OpenShift Container Platform.

. Select *Operators* > *OperatorHub* to access the list of available operators, and select _identity configuration management for Kubernetes_ operator.

. On the _Operator subscription_ page, select the options for your installation:

+
* Namespace: 

  - The identity configuration management for Kubernetes must be installed in its own namespace, or project. 
//The if we actually default to idp-mgmt-config or if a different name can be used.
  - By default, the OperatorHub console installation process creates a namespace titled `idp-mgmt-config`. *Best practice:* Continue to use the `idp-mgmt-config` namespace if it is available.  
  
  - If there is already a namespace named `idp-mgmt-config`, choose a different namespace.

+
* Channel: The channel that you select corresponds to the release that you are installing. When you select the channel, it installs the identified release, and establishes that the future errata updates within that release are obtained.

+
* Approval strategy: The approval strategy identifies the human interaction that is required for applying updates to the channel or release to which you subscribed. 

  - Select *Automatic* to ensure any updates within that release are automatically applied. 
  
  - Select *Manual* to receive a notification when an update is available. If you have concerns about when the updates are applied, this might be best practice for you.

+
*Note:* To upgrade to the next minor release, you must return to the _OperatorHub_ page and select a new channel for the more current release.

. Select *Install* to apply your changes and create the operator. 

+
After the 
identity configuration management for Kubernetes is created, the status for the operator is _Running_ on the _Installed Operators_ page. You can now use the services provided by the identity configuration management 
for Kubernetes. 

[#installing-from-the-cli]
== Installing from the OpenShift Container Platform CLI

. Create a 
identity configuration management for Kubernetes namespace where the operator requirements are contained. Run the following command, where `namespace` is the name for your 
identity configuration management for Kubernetes namespace. The value for `namespace` might be referred to as _Project_ in the OpenShift Container Platform environment:

+
[source,terminal]
----
oc create namespace <namespace>
----

. Switch your project namespace to the one that you created. Replace `namespace` with the name of the 
identity configuration management for Kubernetes namespace that you created in step 1.

+
[source,terminal]
----
oc project <namespace>
----

. Create a YAML file to configure an `OperatorGroup` resource. Each namespace can have only one operator group. Replace `default` with the name of your operator group. Replace `namespace` with the name of your project namespace. See the following example:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: <default>
spec:
  targetNamespaces:
  - <namespace>
----
. Run the following command to create the `OperatorGroup` resource. Replace `operator-group` with the name of the operator group YAML file that you created:

+
[source,terminal]
----
oc apply -f <path-to-file>/<operator-group>.yaml
----
+

. Create a YAML file to configure an OpenShift Container Platform Subscription. Your file should look similar to the following example:

+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: idp-mgmt-operator-subscription
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: release-1.0
  installPlanApproval: Automatic
  name: idp-mgmt-operator
----

+
*Note:* For installing the 
identity configuration management for Kubernetes on infrastructure nodes, the see link:./install_connected.adoc#infra-olm-sub-add-config[ Operator Lifecycle Manager Subscription additional configuration] section.

+
. Run the following command to create the OpenShift Container Platform Subscription. Replace `subscription` with the name of the subscription file that you created:

+
----
oc apply -f <path-to-file>/<subscription>.yaml
----


*Notes:*

- A `ServiceAccount` with a `ClusterRoleBinding` automatically gives cluster administrator privileges to 
identity configuration management for Kubernetes and to any user credentials with access to the namespace where you install 
identity configuration management for Kubernetes.

[#installing-on-infra-node]
== Installing on infrastructure nodes

An OpenShift Container Platform cluster can be configured to contain infrastructure nodes for running approved management components. Running components on infrastructure nodes avoids allocating OpenShift Container Platform subscription quota for the nodes that are running those management components.

After adding infrastructure nodes to your OpenShift Container Platform cluster, follow the link:./install_connected.adoc#installing-from-the-cli[Installing from the OpenShift Container Platform CLI] instructions and add the following configurations to the  Operator Lifecycle Manager Subscription.

[#adding-infra-nodes]
=== Add infrastructure nodes to the OpenShift Container Platform cluster

Follow the procedures that are described in
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/machine_management/creating-infrastructure-machinesets[Creating infrastructure machine sets] in the OpenShift Container Platform documentation. Infrastructure nodes are configured with a Kubernetes `taint` and `label` to keep non-management workloads from running on them.

To be compatible with the infrastructure node enablement provided by 
identity configuration management for Kubernetes, ensure your infrastructure nodes have the following `taint` and `label` applied:

[source,yaml]
----
metadata:
  labels:
    node-role.kubernetes.io/infra: ""
spec:
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
----

[#infra-olm-sub-add-config]
===  Operator Lifecycle Manager Subscription additional configuration

Add the following additional configuration before applying the Operator Lifecycle Manager Subscription:

[source,yaml]
----
spec:
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
----
