[#getting-started]
= Getting started

* <<github-authentication,GitHub authentication>>
* <<ldap-authentication,LDAP authentication>>
* <<command-line-interface,Command line interface>>

[#introduction]
== Introduction

Identity configuration management for Kubernetes is intended to allow you to quickly and easily configure OAuth authentication across your fleet of OpenShift clusters. Through the creation of an AuthRealm custom resource, you are able to specify one or more identity providers (such as GitHub or OpenLDAP) and a placement rule to indicate to which clusters the identity providers should apply. As more clusters are brought under management, their OAuth configuration will be automatically configured simply by matching the specified placement rule.

An identity configuration management operator configuration is composed of: 

* A namespace in which the identity configuration will be defined
* A managedclusterset custom resource which holds the clusters which may be part of the identity configuration.
* A placement custom resource which defines the matching labels to select the clusters.
* A managedclustersetbinding custom resource to bind that placement to the managedclusterset.
* For each identity configuration provider, a secret custom resource containing the client ID and client secret to connect to the identity configuration provider.
* An authrealm custom resource which defines the identiry configuration providers.

We will first walk through setting up your managed cluster set and placement, then prepare the configuration for your preferred identity provider(s).

[#managed-cluster-set-and-placement]
== Preparing your managed cluster set and placement

TODO Chris Ahl please add details here, including bringing clusters under management of a hub.



[#github-authentication]
== GitHub authentication

To use GitHub based authentication, an OAuth application must be defined in GitHub.  

=== GitHub OAuth

. Open a web browser and navigate to https://github.com, go to Settings > Developer Settings > OAuth Apps
(The shortcut is https://github.com/settings/developers)
. Add a *New OAuth App*.  Copy the Client ID and Client Secret values and save them. They will be needed later.  
. Fill in the *Application name* with something to help identify the owner and hub it will be used for.
   NOTE: If you have more than one hub, each one will need its own entry.
. Fill in *Homepage URL*  and *Authorization callback URL* with the OpenShift console URL.  
//TODO Fix this...not sure how user will generate the CRs
   (NOTE: A little bit later we will correct the *Authorization callback URL* value once we have the correctly generated value.)
. Click *Register Application*
*NOTE:* Leave this web page open so you can quickly correct the *Authorization callback URL* value once you have the correct value.


=== AuthRealm custom resource for GitHub
//TODO - need to decide on how to generate and doc CRs



[source,yaml]
----
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: AuthRealm
metadata:
  name: ${AUTHREALM_GITHUB_NAME}
  namespace: ${AUTHREALM_GITHUB_NS}
spec:
  type: dex
  routeSubDomain: ${ROUTE_SUBDOMAIN}
  placementRef:
    name: ${AUTHREALM_GITHUB_NAME}-placement
  identityProviders:
    - name: "${IDP_NAME}"
      mappingMethod: add
      type: GitHub
      github:
        clientID: "${GITHUB_APP_CLIENT_ID}"
        clientSecret:
          name: ${AUTHREALM_GITHUB_NAME}-client-secret
        organizations:
        ${GITHUB_APP_CLIENT_ORG_LINE}

----

[#ldap-authentication]
== LDAP authentication

=== LDAP 

To use LDAP based authentication, an LDAP application must be running in your network.  

=== AuthRealm custom resource for LDAP
[source,yaml]
----
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: AuthRealm
metadata:
  name: ${AUTHREALM_LDAP_NAME}
  namespace: ${AUTHREALM_LDAP_NS}
spec:
  type: dex
  routeSubDomain: ${ROUTE_SUBDOMAIN}
  placementRef:
    name: ${AUTHREALM_LDAP_NAME}-placement
  ldapExtraConfigs:
    openldap:
      baseDN: ${LDAP_USERSEARCH_BASEDN}
      filter: "(objectClass=person)"
  identityProviders:
    - name: openldap
      type: LDAP
      mappingMethod: add
      ldap:
        url: ${LDAP_HOST}
        insecure: true
        bindDN: ${LDAP_BIND_DN}
        bindPassword:
          name: ${AUTHREALM_LDAP_NAME}-ldap-secret
          namespace: ${AUTHREALM_LDAP_NS}
        attributes:
          id:
            - DN
          preferredUsername:
            - mail
          name:
            - cn
          email:
            - mail
----

[#Command line interface]
== Command line interface

AuthRealm configuration can be created through the link:https://github.com/open-cluster-management/cm-cli[cm-cli].

[source,terminal]
----
cm create authrealm --values <values.yaml>
----

. Fill the template form
+ 
The template can be retreived by running:
+
[source,terminal]
----
cm create authrealm -h
----
+
Fill the template and save it as for example my-authrealm.yaml
+
[source,yaml]
----
authRealm:
  # The name of the authrealm, can be override using the --name parameter
  name: 
  # The namespace where the authrealm must be created, can be override using the --namespace
  namespace:
  # The strategy type, only dex is supported, can be override using --type
  type: dex
  # The routeSubDomain to use, can be override using --route-sub-domain
  routeSubDomain:
  # The placement rule to use, if not present then a new one will be created
  # in the authrealm namespace and having for labelSelector the matchLabels below.
  # It can be overridden using --placement
  placement:
  # The matchLabels to use to build the placement if not provided
  # For example:
  # matchLabels:
  #  authdeployment: east
  matchLabels: 
  # The managedClusterSet to link the placement to, can be override using --cluster-set
  managedClusterSet:
  # The managedClusterSetBinding, if not present then it will be created to bind
  # the provided placement with the managedClusterSet
  # It can be overridden using --cluster-set-binding
  managedClusterSetBinding:
  # The list of identity providers
  identityProviders:
  # Example for github, this section will be copied into the authrealm CR.
  # Reference: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_oauth.crd.yaml#L80
  # The identity provider name
  - name: my-github-idp 
    # The mappingMethod could be add, claim or lookup
    mappingMethod: claim 
    # The identity provider type, here GitHub
    type: GitHub 
    # The github specifics
    github:
      # The client ID of the github app
      clientID: 
      # The github app secret, the cm-cli will create a local secret with it
      clientSecret:
      # Lists of GitHub Organizations (optionals)
      organizations:
      - myorg
    #,,,,
  # Example for LDAP, this section will be copied into the authrealm CR.
  # Reference: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_oauth.crd.yaml#L215
  # The identity provider name
  - name: my-ldap-idp
    # The mappingMethod could be add, claim or lookup
    mappingMethod: claim
    # The identity provider type, here LDAP
    type: LDAP
    # The ldap specifics
    ldap:
      # The LDAP server url
      url:
      # The bind Domain name
      bindDN:
      # The bind password, the cm-cli will create a local secret with it
      bindPassword:
    #....
  # Extra supported ldap configuration for the dex server
  # 
  ldapExtraConfigs:
    # The name of the ldap identity provider
    my-ldap-idp: 
      # The base Domain name
      baseDN: 
      filter:
----

. Create the authrealm
.. Create directly
+
[source,terminal]
----
cm create authrealm --values my-authrealm.yaml 
----
.. Create a file and then apply
+
Options --dry-run with --output-file can be used to get the rendered file
+
[source,terminal]
----
cm create authrealm --values my-authrealm.yaml --dry-run --output-file my-authrealm-yamls.yaml
----
+
Then the my-authrealm-yamls.yaml can be applied using
+
[source,terminal]
----
oc apply -f my-authrealm-yamls.yaml
----