[#getting-started]
= Getting started

* <<github-authentication,GitHub authentication>>
* <<ldap-authentication,LDAP authentication>>
* <<command-line-interface,Command line interface>>

[#introduction]
== Introduction

Identity configuration management for Kubernetes is intended to allow you to quickly and easily configure OAuth authentication across your fleet of OpenShift clusters. Through the creation of an AuthRealm custom resource, you are able to specify one or more identity providers (such as GitHub or OpenLDAP) and a placement rule to indicate to which clusters the identity providers should apply. As more clusters are brought under management, their OAuth configuration will be automatically configured simply by matching the specified placement rule.

An identity configuration management operator configuration is composed of: 

* A namespace in which the identity configuration will be defined
* A managedclusterset custom resource which holds the clusters which may be part of the identity configuration.
* A placement custom resource which defines the matching labels to select the clusters.
* A managedclustersetbinding custom resource to bind that placement to the managedclusterset.
* For each identity configuration provider, a secret custom resource containing the client ID and client secret to connect to the identity configuration provider.
* An authrealm custom resource which defines the identiry configuration providers.

We will first walk through setting up your managed cluster set and placement, then prepare the configuration for your preferred identity provider(s).

[#managed-cluster-set-and-placement]
== Preparing your managed cluster set and placement

TODO Chris Ahl please add details here, including bringing clusters under management of a hub.

[#creating-auth-realm]
== Creating your AuthRealm

The AuthRealm custom resoure specifies a combination of one or more https://docs.openshift.com/container-platform/4.8/authentication/understanding-identity-provider.html[identity providers] and a placement that determines to which managed clusters the identity provider(s) should be applied.

An AuthRealm resource example is as follows:
[source,yaml]
----
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: AuthRealm
metadata:
  name: identity-config-developers
  namespace: identity-config-authrealm
spec:
  identityProviders:
  - github:
      clientID: 41c30d83fd1b4774f871
      clientSecret:
        name: identitatem-github-client-secret
      organizations:
      - identitatem
    mappingMethod: claim
    name: identitatem-developers
    type: GitHub
  placementRef:
    name: dev-clusters-placement
  routeSubDomain: identitatem-devs
  type: dex
----
The `identityProviders` list values directly correspond to OpenShift Container Platform's https://docs.openshift.com/container-platform/4.8/authentication/understanding-identity-provider.html[identity provider] configuration. Only GitHub and LDAP are supported in this Technology Preview. Take special note of the https://docs.openshift.com/container-platform/4.8/authentication/understanding-identity-provider.html#identity-provider-parameters_understanding-identity-provider[`mappingMethod`] field, which controls how mappings are established between the provider’s identities and User objects.

The `placementRef` contains the name of the Placement custom resource located in the same namespace as the AuthRealm that will determine to which clusters this AuthRealm will apply.

The `routeSubDomain` must be unique among all AuthRealms on the hub cluster and is used to form the Issuer URL of the intermediary OpenID connect server that is installed and configured automatically on the hub cluster by identity configuration management in order to achieve fleet-wide identity configuration. The managed clusters' cluster OAuth configurations connect to this OpenID connect server via the Issuer URL, rather than connecting to the desired identity provider directly.

The `type` field must be set to `dex` for the Technology Preview. The Technology Preview leverages Dex under the covers as described above to achieve fleet-wide identity configuration.


[#github-authentication]
== GitHub authentication

To use GitHub based authentication, an OAuth application must be defined in GitHub.  

=== GitHub OAuth

. The GitHub Oauth app can be created in your personal profile or in a Github organization that you are an administrator for.
  * To create a GitHub Oauth app in your personal profile: Open a web browser and navigate to https://github.com, go to _Settings > Developer Settings > OAuth Apps_ (The shortcut is https://github.com/settings/developers)
  * To create a GitHub Oauth app in a GitHub organization that you are an administrator for: Open a web browser and navigate to https://github.com/{organization_name}, go to _Settings > Developer Settings > OAuth Apps_ (The shortcut is https://github.com/{organization_name}/settings/developers)
. Add a *New OAuth App*. In the new OAuth app, *Generate a new client secret*. Copy the Client ID and Client Secret values and save them. They will be needed later.  
. Fill in the *Application name* with something to help identify the owner and hub it will be used for.
   NOTE: If you have more than one hub, each one will need its own entry.
. Fill in *Homepage URL*  and *Authorization callback URL* with the OpenShift console URL.  
//TODO Fix this...not sure how user will generate the CRs
   (NOTE: A little bit later we will correct the *Authorization callback URL* value once we have the correctly generated value.)
. Click *Register Application*
*NOTE:* Leave this web page open so you can quickly correct the *Authorization callback URL* value once you have the correct value.

=== AuthRealm custom resource for GitHub
An example of an AuthRealm custom resource configured for the Github identity provider is provided below. Make note of the `identityProviders` field and the configuration of the `github` identity provider under it:
[source,yaml]
----
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: AuthRealm
metadata:
  name: identity-config-developers
  namespace: identity-config-authrealm
spec:
  identityProviders:
  - github:
      clientID: 41c30d83fd1b4774f871
      clientSecret:
        name: identitatem-github-client-secret
      organizations:
      - identitatem
    mappingMethod: claim
    name: identitatem-developers
    type: GitHub
  placementRef:
    name: dev-clusters-placement
  routeSubDomain: identitatem-devs
  type: dex
----

The `identityProviders` list contains the configurations for one or more identity providers. The example above contains a single identity provider (GitHub).
An entry under `identityProviders` has the following fields:

- `name` contains the unique name that is used to identify the identity provider.
- `type` specifies the identity provider type and it is set to GitHub.
- `mappingMethod` (add, claim or lookup) controls how mappings are established between this provider’s identities and User objects.
- `github` contains the GitHub specific configurations:
  * `clientID` contains the client ID of a registered GitHub OAuth application.
  * `clientSecret` contains a reference to an OpenShift Container Platform Secret object containing the client secret issued by GitHub. 
  * `organizations` contains a list of organizations to authenticate the user against. This field can be left blank to skip authentication against specific GitHub organizations. If organizations are specified in the config then the user must be a member of at least one of the specified orgs. +
*Note*: If the GitHub OAuth application is not owned by an organization specified in `organizations`, an organization owner must grant third-party access to use this option. This can be done in two ways:
    ** by the GitHub organization's administrator from the GitHub organization settings, 
    ** or, during the first GitHub login when the user will be presented with a UI to explicitly request access to the GitHub organization. The request will flow to the GitHub organization's administrator for approval and the user will only be able to login after the request for access is approved.

[#ldap-authentication]
== LDAP authentication

=== LDAP 

To use LDAP based authentication, an LDAP application must be running in your network.  

=== AuthRealm custom resource for LDAP
An example of an AuthRealm custom resource configured for the LDAP identity provider is provided below. Make note of the `identityProviders` field and the configuration of the `ldap` identity provider under it:
[source,yaml]
----
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: AuthRealm
metadata:
  name: authrealm-ldap
  namespace: authrealm-ldap-ns
spec:
  type: dex
  routeSubDomain: identitatem-devs
  placementRef:
    name: authrealm-ldap-placement
  ldapExtraConfigs:
    openldap:
      baseDN: "dc=example,dc=com"
      filter: "(objectClass=person)"
  identityProviders:
    - name: openldap
      type: LDAP
      mappingMethod: add
      ldap:
        url: a438af6d7959d448fb56138b20e2bbba-2094583330.us-east-1.elb.amazonaws.com:636
        insecure: false
        bindDN: cn=Manager,dc=example,dc=com
        ca:
          name: authrealm-ldap-ca
          namespace: authrealm-ldap-ns
        bindPassword:
          name: authrealm-ldap-secret
          namespace: authrealm-ldap-ns
        attributes:
          id:
            - DN
          preferredUsername:
            - mail
          name:
            - cn
          email:
            - mail

----

The `identityProviders` list contains the configurations for one or more identity providers. The example above contains a single identity provider (LDAP).
An entry under `identityProviders` has the following fields:

- `name` contains the unique name that is used to identify the identity provider.
- `type` specifies the identity provider type and it is set to LDAP.
- `mappingMethod` (add, claim or lookup) controls how mappings are established between this provider’s identities and User objects.
- `ldapExtraConfigs` contains extra server configuration setting for LDAP, the key being the idp.name
  * `baseDN` contains information to start the LDAP user search from. For example "cn=users,dc=example,dc=com"
  * `filter` contains optional filter to apply when searching the directory. For example "(objectClass=person)"
- `ldap` contains the LDAP specific configurations:
  * `url` contains the LDAP host and optional port of the LDAP server
  * `bindDN` contains an optional DN to bind with during the search phase.
  * `bindPassword` contains an optional reference to a secret by name containing a password to bind with during the search phase.
*Note*: bindDN and bindPassword need to be provided if the LDAP server requires authentication for search.
  * `ca` contains reference to the secret containing a trusted Root CA file - file name and format: "ca.crt"
*Note*: If the server uses self-signed certificates, include files with names "tls.crt" and "tls.key" (representing client certificate and key) in the same secret
- `attributes` maps LDAP attributes to identities
  * `id` is the list of attributes whose values should be used as the user ID. Required. First non-empty attribute is used. At least one attribute is required. If none of the liste attribute have a value, authentication fails. LDAP standard identity attribute is "dn"
  * `preferredUsername` is the list of attributes whose values should be used as the preferred username. LDAP standard login attribute is "uid"
  * `name` is the list of attributes whose values should be used as the display name. Optional. If unspecified, no display name is set for the identity. LDAP standard display name attribute is "cn"
  * `email` is the list of attributes whose values should be used as the email address. Optional. If unspecified, no email is set for the identity 
----

[#Command line interface]
== Command line interface

AuthRealm configuration can be created through the link:https://github.com/open-cluster-management/cm-cli[cm-cli].

[source,terminal]
----
cm create authrealm --values <values.yaml>
----

. Fill the template form
+ 
The template can be retreived by running:
+
[source,terminal]
----
cm create authrealm -h
----
+
Fill the template and save it as for example my-authrealm.yaml
+
[source,yaml]
----
authRealm:
  # The name of the authrealm, can be override using the --name parameter
  name: 
  # The namespace where the authrealm must be created, can be override using the --namespace
  namespace:
  # The strategy type, only dex is supported, can be override using --type
  type: dex
  # The routeSubDomain to use, can be override using --route-sub-domain
  routeSubDomain:
  # The placement rule to use, if not present then a new one will be created
  # in the authrealm namespace and having for labelSelector the matchLabels below.
  # It can be overridden using --placement
  placement:
  # The matchLabels to use to build the placement if not provided
  # For example:
  # matchLabels:
  #  authdeployment: east
  matchLabels: 
  # The managedClusterSet to link the placement to, can be override using --cluster-set
  managedClusterSet:
  # The managedClusterSetBinding, if not present then it will be created to bind
  # the provided placement with the managedClusterSet
  # It can be overridden using --cluster-set-binding
  managedClusterSetBinding:
  # The list of identity providers
  identityProviders:
  # Example for github, this section will be copied into the authrealm CR.
  # Reference: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_oauth.crd.yaml#L80
  # The identity provider name
  - name: my-github-idp 
    # The mappingMethod could be add, claim or lookup
    mappingMethod: claim 
    # The identity provider type, here GitHub
    type: GitHub 
    # The github specifics
    github:
      # The client ID of the github app
      clientID: 
      # The github app secret, the cm-cli will create a local secret with it
      clientSecret:
      # Lists of GitHub Organizations (optionals)
      organizations:
      - myorg
    #,,,,
  # Example for LDAP, this section will be copied into the authrealm CR.
  # Reference: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_oauth.crd.yaml#L215
  # The identity provider name
  - name: my-ldap-idp
    # The mappingMethod could be add, claim or lookup
    mappingMethod: claim
    # The identity provider type, here LDAP
    type: LDAP
    # The ldap specifics
    ldap:
      # The LDAP server url
      url:
      # The bind Domain name
      bindDN:
      # The bind password, the cm-cli will create a local secret with it
      bindPassword:
    #....
  # Extra supported ldap configuration for the dex server
  # 
  ldapExtraConfigs:
    # The name of the ldap identity provider
    my-ldap-idp: 
      # The base Domain name
      baseDN: 
      filter:
----

. Create the authrealm
.. Create directly
+
[source,terminal]
----
cm create authrealm --values my-authrealm.yaml 
----
.. Create a file and then apply
+
Options --dry-run with --output-file can be used to get the rendered file
+
[source,terminal]
----
cm create authrealm --values my-authrealm.yaml --dry-run --output-file my-authrealm-yamls.yaml
----
+
Then the my-authrealm-yamls.yaml can be applied using
+
[source,terminal]
----
oc apply -f my-authrealm-yamls.yaml
----
