[#getting-started]
= Getting started

* <<github-authentication,GitHub authentication>>
* <<ldap-authentication,LDAP authentication>>

[#introduction]
== Introduction

Coming: Architecture and intro.

An identity configuration management operator configuration is composed of: 
* A namespace custom resource in which the identity configuration will be defined
* A managedclusterset custom resource which holds the clusters which must be part of the identity configuration.
* A placement custom resource which defines the matching labels to select the clusters.
* A managedclustersetbinding custom resource to bind that placement to the managedclusterset.
* For each identity configuration provider, a secret custom resource containing the client ID and client secret to connect to the identity configuration provider.
* An authrealm custom resource which defines the identiry configuration providers.


Before you install identity configuration management for Kubernetes, review the system configuration requirements and settings at link:../install/requirements.adoc#requirements-and-recommendations[Requirements and recommendations]. With a supported version of OpenShift Container Platform installed and running on your hub cluster, you can proceed with link:../install/install_connected.adoc#installing-while-connected-online[Installing while connected online].


[#github-authentication]
== GitHub authentication


[#ldap-authentication]
== LDAP authentication

[#Command line interface]
== Command line interface

Authrealm configuration can be created through the link:https://github.com/open-cluster-management/cm-cli[cm-cli].

[source,terminal]
----
cm create authrealm --values <values.yaml>
----

. Fill the template form
+ 
The template can be retreived by running:
+
[source,terminal]
----
cm create authrealm -h
----
+
Fill the template and save it as for example my-authrealm.yaml
+
[source,yaml]
----
authRealm:
  # The name of the authrealm, can be override using the --name parameter
  name: 
  # The namespace where the authrealm must be created, can be override using the --namespace
  namespace:
  # The strategy type, only dex is supported, can be override using --type
  type: dex
  # The routeSubDomain to use, can be override using --route-sub-domain
  routeSubDomain:
  # The placement rule to use, if not present then a new one will be created
  # in the authrealm namespace and having for labelSelector the matchLabels below.
  # It can be overridden using --placement
  placement:
  # The matchLabels to use to build the placement if not provided
  # For example:
  # matchLabels:
  #  authdeployment: east
  matchLabels: 
  # The managedClusterSet to link the placement to, can be override using --cluster-set
  managedClusterSet:
  # The managedClusterSetBinding, if not present then it will be created to bind
  # the provided placement with the managedClusterSet
  # It can be overridden using --cluster-set-binding
  managedClusterSetBinding:
  # The list of identity providers
  identityProviders:
  # Example for github, this section will be copied into the authrealm CR.
  # Reference: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_oauth.crd.yaml#L80
  # The identity provider name
  - name: my-github-idp 
    # The mappingMethod could be add, claim or lookup
    mappingMethod: claim 
    # The identity provider type, here GitHub
    type: GitHub 
    # The github specifics
    github:
      # The client ID of the github app
      clientID: 
      # The github app secret, the cm-cli will create a local secret with it
      clientSecret:
      # Lists of GitHub Organizations (optionals)
      organizations:
      - myorg
    #,,,,
  # Example for LDAP, this section will be copied into the authrealm CR.
  # Reference: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_oauth.crd.yaml#L215
  # The identity provider name
  - name: my-ldap-idp
    # The mappingMethod could be add, claim or lookup
    mappingMethod: claim
    # The identity provider type, here LDAP
    type: LDAP
    # The ldap specifics
    ldap:
      # The LDAP server url
      url:
      # The bind Domain name
      bindDN:
      # The bind password, the cm-cli will create a local secret with it
      bindPassword:
    #....
  # Extra supported ldap configuration for the dex server
  # 
  ldapExtraConfigs:
    # The name of the ldap identity provider
    my-ldap-idp: 
      # The base Domain name
      baseDN: 
      filter:
----

. Create the authrealm
.. Create directly
+
[source,terminal]
----
cm create authrealm --values my-authrealm.yaml 
----
.. Create a file and then apply
+
Options --dry-run with --output-file can be used to get the rendered file
+
[source,terminal]
----
cm create authrealm --values my-authrealm.yaml --dry-run --output-file my-authrealm-yamls.yaml
----
+
Then the my-authrealm-yamls.yaml can be applied using
+
[source,terminal]
----
oc apply -f my-authrealm-yamls.yaml
----