[#requirements-and-recommendations]
= Requirements and recommendations

Before you install identity configuration management for Kubernetes technology preview, review the following system configuration requirements and settings:

* <<supported-operating-systems-and-platforms,Supported operating systems and platforms>>
* <<sizing-recommendations,Sizing recommendations>>
* <<security-requirements,Security requirements>>
* <<network-configuration,Network configuration>>

*Note:* There is no console for the Technology Preview version of this product.

[#supported-operating-systems-and-platforms]
== Supported operating systems and platforms for hub clusters and managed clusters

The identity configuration management tech preview requires the https://stolostron.github.io/mce-docs/[multicluster engine for Kubernetes 1.0 Technology Preview] or https://www.redhat.com/en/technologies/management/advanced-cluster-management[Red Hat Advanced Cluster Management for Kubernetes 2.4].

Both the hub and managed clusters must be running OpenShift Container Platform at the levels supported by your chosen multicluster solution, multicluster engine or Advanced Cluster Management. Red Hat OpenShift Managed cloud services are not supported for this technology preview.

*Note:* Only OpenShift Container Platform 4.8 is supported for the hub, a minimum of 4.8.12 is required due to https://bugzilla.redhat.com/show_bug.cgi?id=1969902[Bugzilla 1969902]. OpenShift Container Platform 4.9 is not currently supported. 

[#sizing-recommendations]
== Sizing recommendations

If you are using multicluster engine, you will need a minimum of 1 node with 8 CPU, 32Gb of memory, and 100Gb disk.

If you are using Advanced Cluster Management, follow the RHACM sizing requirements.

[#security-requirements]
== Security requirements

[#openid-server-certificate]
=== Securing OAuth requests to the OpenID Connect identity provider

The identity configuration management operator instantiates one or more OpenID Connect identity providers under the covers to enable fleet-wide authentication. OAuth requests from the managed clusters to these identity providers must be secured using valid, signed certificates. This can be accomplished by https://docs.openshift.com/container-platform/4.8/security/certificates/replacing-default-ingress-certificate.html#replacing-default-ingress[replacing the default ingress certificate] on the hub cluster or by providing a certicate in an AuthRealm custom resource. 
// TODO: Add link to directions for specifying cert in AuthRealm CRD


[#network-configuration]
== Network configuration

Configure your network settings to allow the connections in the following sections. These network configurations are in addition to those required by multicluster engine and Advanced Cluster Management.

[#network-configuration-hub]
=== Hub cluster networking requirements

For the hub cluster networking requirements, see the following table:

|===
| Direction | Connection | Port (if specified)

| Outbound
| GitHub or GitHub Enterprise API. This is only required if you are using GitHub as an identity provider.
| 

| Outbound
| LDAP server (Example: OpenLDAP or Azure Active Directory managed domain). This is only required if you are using LDAP as an identity provider.
| 

| Inbound
| The OpenID Connect issuer from the managed cluster.
| 443

|===

[#network-configuration-managed]
=== Managed cluster networking requirements

For the managed cluster networking requirements, see the following table:

|===
| Direction | Connection | Port (if specified)

| Outbound
| OpenID Connect issuer running on the hub cluster
| 443

|===



